fix: Issue 402 (GroovyBracketInsertionCompleter shall not treat a ${ as a closure))
de-jcup/egradle pull request #405
Opened 2022-03-01 04:55 UTC by BeckerFrank

This Pull request is for Issue 402 (https://github.com/de-jcup/egradle/issues/402)

2022-03-06 21:04 UTC, de-jcup requested changes
Hello @BeckerFrank ,
thank you for contributing again!

Your solution works well, but I have some minor change requests. See my comments.
After changes are done I will merge your PR.

PS: I changed your PR description a bit  - so the PR 
- is automatically linked with the issue
- issue texts are shown completely. 
- merging the PR will automatically close the issue

See my text changes there (it's just a `This PR closes #$nr`)

2022-03-07 02:49 UTC, BeckerFrank commented on egradle-plugin-main/src/main/java-eclipse/de/jcup/egradle/eclipse/ui/GroovyBracketInsertionCompleter.java
> +			String charBeforBracket = document.get(offset - 2, 1);
Done!
See next commit!

2022-03-07 02:49 UTC, BeckerFrank commented on egradle-plugin-main/src/main/java-eclipse/de/jcup/egradle/eclipse/ui/GroovyBracketInsertionCompleter.java
> +			e2.printStackTrace();
Done!
See next commit!

2022-03-14 05:40 UTC, de-jcup approved these changes
Looks fine for me.

2022-03-14 05:46 UTC, de-jcup commented
@BeckerFrank : I will squash and merge by one commit - so I can shorten the messages (they are longer than 50 characters ) see https://git-scm.com/docs/git-commit#_discussion for details. But you will still be the author of the change inside the commit history.

I do all of my commits in such way:

```
This is my short message (up to 50 chars max)

- here are detailed informations (the empty line before makes formatting in command line much better)
- you calso use some simple markup here. At least github does render this very good and it's good readable
- eclipse does give you also hints about this behaviour inside the `commit message` field of the `git staging` view
```

2022-03-14 05:49 UTC, merged